### ISSUE TITLE
making dockerspawner example work with docker-compose

### ISSUE THREAD

**Issue by phaustin** [phaustin/jupyterhub_basics#1]
The following is working fine for me:

```
cd jupyterhub_basics/examples/simple
./bringdown.sh
docker-compose pull notebook
docker-compose build jupyterhub
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock --net jupyterhub --name jupyterhub -p8000:8000 hub
```

and if I go to localhost:8000  I can log in as anyone and get a notebook.

What isn't working:

I'm still missing something in the docker-compose.yml file, because if I replace the `docker run` with

`docker-compose up`

My login attempt times out trying to spawn the notebook image.

**Comment by kafonek** [comment]
@phaustin I believe when docker-compose creates the network it names the network `{directory}_default`.  When you're running your stand-alone `docker run` command, you're telling it to join the network `jupyterhub` but when you're running docker-compose it is joining the network `jupyterhub_default` (if your directory is named jupyterhub).  You can inspect this by running `docker-compose up` and then `docker network ls`.

In your jupyterhub_config.py, you've hard-coded the network name to `jupyterhub`.

One option is to specify the network name in your `docker-compose.yml` like:
```
networks:
  jupyterhub:
    name: "jupyterhub"
```

Another option is to change `c.DockerSpawner.network_name` to `jupyterhub_default` (or whatever `{directory}_default` you intend to run it in).

**Comment by phaustin** [comment]
Thanks @kafonek -- that was exactly the problem -- fixed with https://github.com/phaustin/jupyterhub_basics/commit/88351c92ffe94823b54b5dac8bfc183a4efca856
